KMP algorithm

kmp algo done
please review @abhaysinghr516

Create KMP algorithm

---

kadane's algorithm

Create kadane's algorithm

---

Tree Traversal/PostOrder_Traversal.java

PostOrder traversal

---

Merge Sort

Create Merge Sort

---

Quick Sort Algorithm

Create Quick Sort Algorithm

---

Merge Sort Algorithm/MergeSort.java

Commited succesfully

---

Selection Sort Algortihm/SelectionSort.cpp

Added code for selection sort in cpp.

added SelectionSort.cpp

---

Merge Sort Algorithm/merge_sort.go

fix #18 
Added merge_sort.go file in Merge Sort Algorithm folder

merge_sort.go added

---

Quicksort Algorithm/C/quick_sort.c

fix #22 
Added quick_sort.c file in Quicksort Algorithm/C folder

quick_sort.c added

---

Quicksort Algorithm/Go/quick_sort.go

fix #24 
Added quick_sort.go file in Quicksort Algorithm/Go folder

quick_sort.go file added

---

BubbleSortAlgorithm/Javascript/BubbleSort.js

What does this PR do?
Added bubble sort algorithm for javascript
related #71

Added Bubble Sort Algorithm for Javascript

---

BubbleSortAlgorithm/C/BubbleSort.c

What does this PR do?
Added bubble sort algorithm in C
related #67

Added Bubble Sort Algorithm in C

---

BubbleSortAlgorithm/C++/BubbleSort.cpp

What does this PR do?
Added bubble sort algorithm in C++
related #68

Added Bubble Sort Algorithm in C++

---

BubbleSortAlgorithm/Go/BubbleSort.go

I have added an implementation of the Bubble Sort algorithm using Golang which will fix issue #69.
Please let me know if there are any issues with the pull request and I would be happy to fix/adjust.

Added golang for bubble sort for issue #69

---

Kruskal's Algorithm/Kruskal's Algorithm(Python).py

Added `Kruskal's Algorithm(Python).py` file to the `Kruskal's Algorithm` folder
This file implements Kruskal's algorithm using Union-Find in python. It includes 1 test case at the end commented out and has been thoroughly tested for edge cases. In addition, it handles the case when the input graph is not connected (i.e. MST cannot be found).

added python implementation of kruskal's algo

---

Merge Sort Algorithm/merge_sort.py

The merge sort algorithm file is written in python and exists under merge sort algorithm folder
This is PR for issue #21

Merge Sort Algorithm in Python

---

Union Find Algorithm/union_find.js

What does this PR do?
Added union find algorithm in javascript
related #91

Add Union Find Algorithm in Javascript

---

Union Find Algorithm/union_find.go

Implemented Union Find Algorithm using Go
Closes #89

feat: Implemented Union Find Algorithm using Go

---

Union Find Algorithm/union_find.c

Implemented Union Find Algorithm using Go
Closes #87

feat: Implemented Union Find Algorithm using C

---

Bellman-ford.r

added Bellman Ford Algorithm in Rust

Bellman-Ford

---

Binary Search Algorithm/Rust/Binary_Search_Algorithm.rs

Fix: #101 
Added Binary_Search_Algorithm.rs

Fix : #101 Added Binary_Search_Algorithm.rs

---

Binary Search Algorithm/Rust/Binary_Search_Algorithm.rs
Breadth First Search(BFS) Algorithm/Rust/Breadth_First_Search_Algorithm.rs
Counting Sort Algortihm/Rust/Counting_Sort_Algorithm.rs

Fix: #103 Breadth_First_Algorithm in Rust added

Fix: #103 Breadth_First_Algorithm in Rust added

---

Binary Search Algorithm/Rust/Binary_Search_Algorithm.rs
Breadth First Search(BFS) Algorithm/Rust/Breadth_First_Search_Algorithm.rs
Counting Sort Algortihm/Rust/Counting_Sort_Algorithm.rs

Fix : #104 Added Counting Sort Algorithm in Rust

Fix : #104 Added Counting Sort Algorithm in Rust

---

Binary Search Algorithm/Rust/Binary_Search_Algorithm.rs
Breadth First Search(BFS) Algorithm/Rust/Breadth_First_Search_Algorithm.rs
Counting Sort Algortihm/Rust/Counting_Sort_Algorithm.rs
Depth First Search(DFS) Algorithm/Rust/Depth_Firtst_Search_Algorithm.rs

Fix: #105 Depth_First_Search_Algorithm in Rust added

Fix: #105 Depth_First_Search_Algorithm in Rust added

---

Binary_search.r

added Binary Search algorithm in Rust

Binary Search

---

Boyer-Moore Majority Vote Algortihm/Rust/Boyer-Moore-Majority-Vote-Algorithm.rs

Fix: #102 Boyer Moore majority vote algorithm in Rust added

 Fix: #102 Boyer Moore majority vote algorithm in Rust added

---

Merge Sort Algorithm/C++/Triway_merge_sort.cpp

Created a file (_\Merge Sort Algorithm\C++\Triway_merge_sort.cpp_) that implements merge sort with a three-way variation instead of the classic merge sort in C++.

implemented three way variation of merge sort

---

TopologicalSortAlgorithm/Topo_Sort.cpp
TopologicalSortAlgorithm/Topo_Sort.py

- Fixed issue: #125 
Topological sort is an algorithm used to order the vertices of a directed acyclic graph (DAG) in a linear sequence such that for every directed edge ( u \rightarrow v ), vertex ( u ) appears before ( v ) in the ordering. This is particularly useful in scenarios like task scheduling, where certain tasks must be completed before others, and in resolving dependencies in systems like build processes or course prerequisites. The algorithm can be implemented using Depth-First Search (DFS) or Kahn’s algorithm, ensuring that all dependencies are respected in the final order.

Added Topological sorting in C++ and Python

---

Tree Traversal Algorithm/Python/Tree-Traversal-Algorithm.py

- Implements preorder, inorder, and postorder traversals
- Includes both recursive and iterative implementations
- Features comprehensive docstrings and type hints
- Provides example usage and testing functions
- Time complexity: O(n) for all traversals
- Space complexity: O(h) recursive, O(n) iterative
Fixes #hacktoberfest

Add Tree Traversal Algorithm implementation in Python

---

Tree Traversal Algorithm/JavaScript/Tree-Traversal-Algorithm.js

- Implements preorder, inorder, and postorder traversals
- Includes both recursive and iterative implementations
- Features TreeNode class and modular function exports
- Provides comprehensive example usage and testing
- Time complexity: O(n) for all traversals
- Space complexity: O(h) recursive, O(n) iterative
Fixes #hacktoberfest

Add Tree Traversal Algorithm implementation in JavaScript

---

Kadane's Algorithm/C/Kadanes-Algorithm.c
Kadane's Algorithm/JavaScript/Kadanes-Algorithm.js
Kadane's Algorithm/Python/Kadanes-Algorithm.py
Tree Traversal Algorithm/Go/Tree-Traversal-Algorithm.go
Tree Traversal Algorithm/Rust/Tree-Traversal-Algorithm.rs

Tree Traversal Algorithm:
- Go implementation with recursive and iterative approaches
- Rust implementation with memory safety and comprehensive tests
Kadane's Algorithm:
- C implementation with subarray indices tracking
- JavaScript implementation with functional programming features
- Python implementation with comprehensive documentation
All implementations include:
- Detailed documentation and examples
- Multiple algorithmic approaches
- Comprehensive test cases
- Time/Space complexity analysis
Fixes #hacktoberfest

Add comprehensive algorithm implementations for Hacktoberfest

---

Radix Sort Algorithm/C++/Radix-Sort-Algorithm.cpp
Radix Sort Algorithm/README.md

This PR adds a complete implementation of the Radix Sort algorithm in C++ & closes #141 
- ✅ Complete C++ implementation of Radix Sort algorithm
- ✅ Comprehensive README.md with algorithm details
- ✅ Time complexity: O(d × (n + k))
- ✅ Space complexity: O(n + k)
- ✅ Working test cases included
- ✅ Uses counting sort as stable subroutine
- Non-comparative integer sorting algorithm
- Stable sorting (maintains relative order of equal elements)
- Processes digits from LSD to MSD
- Suitable for large datasets with fixed-digit numbers
- ✅ Compiled and tested with multiple test cases
- ✅ Correctly sorts arrays: [170, 45, 75, 90, 2, 802, 24, 66]
- ✅ Handles edge cases and different array sizes
Fixes: Adds new efficient sorting algorithm for integer arrays

Add Radix Sort Algorithm implementation in C++

---

website/algorithms.json

The program prompts for user input, reads an integer, and performs an optimized check for primality by iterating up to the square root of the number. It correctly handles the edge case where numbers less than or equal to 1 are not considered prime.

feat: Add prime number checking and  Update algorithms.json

---

KMP Algorithm/Java/kmp_algo.java
KMP Algorithm/Python/kmp_algo.py

Added python and  java implementation for kmp string search algorithm

---

Sieve of Eratosthenes Algorithm/C++/sieve_of_eratosthenese.cpp
Sieve of Eratosthenes Algorithm/Java/sieve_of_eratosthenes.java
Sieve of Eratosthenes Algorithm/Python/sieve_of_eratosthense.py
Sieve of Eratosthenes Algorithm/README.md

[FEAT] : Sieve of Eratosthenes Algorithm
